### ISSUE TITLE
Background color and dimensions won't add up

### ISSUE THREAD

**Issue by MauricioKruijer** [TOVS/tovs_website_2017#27]
## According design (expected)
<img width="1232" alt="screen shot 2017-06-06 at 16 50 22" src="https://cloud.githubusercontent.com/assets/224625/26835613/f7814f58-4ad8-11e7-8001-cfce8ce3c3f8.png">

## Actual implementation 
<img width="1509" alt="screen shot 2017-06-06 at 16 53 17" src="https://cloud.githubusercontent.com/assets/224625/26835632/03c12248-4ad9-11e7-99a2-b87442318de9.png">
<img width="1527" alt="screen shot 2017-06-06 at 16 53 07" src="https://cloud.githubusercontent.com/assets/224625/26835642/0997b36c-4ad9-11e7-8c8b-9c2332529584.png">

**Comment by MauricioKruijer** [comment]
## New result
<img width="1313" alt="screen shot 2017-06-06 at 19 00 27" src="https://user-images.githubusercontent.com/224625/26841722-b15b3036-4aea-11e7-9da2-df44ea9bb4cb.png">
<img width="1244" alt="screen shot 2017-06-06 at 19 00 34" src="https://user-images.githubusercontent.com/224625/26841728-b649452e-4aea-11e7-9c4f-93e13d6643e4.png">

@OrpheTana In de PR is de `padding-top: 85px` en de `padding-bottom: 97px`, dit zorgt ervoor dat het matched met de hoogte van de section in het design (346px). Zal ik het laten zo? Of zal ik top/bottom padding op 85px zetten?

**Comment by OrpheTana** [comment]
@MauricioKruijer top/bottom padding 85px. Laten we dat aanhouden voor alle sections met tekst in het geselecteerd werk gedeelte van de site. Houden we het consistent. Lekker pixel pushen 😄   

Dit is een screenshot van top/bottom padding 85px aan allebei de kanten.  
![screen shot 2017-06-09 at 00 19 25](https://user-images.githubusercontent.com/9799852/26953242-872735f6-4ca9-11e7-8180-d2e7145ef7ae.png)

Dit is tekst section met minder tekst. Ook de padding 85px aan allebei de kanten.  
![screen shot 2017-06-09 at 00 20 48](https://user-images.githubusercontent.com/9799852/26953258-99ea4ee4-4ca9-11e7-8faa-88aa484237f3.png)
